#!/usr/bin/env bash
set -e
source /opt/ros/jazzy/setup.bash
if [ -f /workspace/dobotmagician/ros2_ws/install/setup.bash ]; then
  source /workspace/dobotmagician/ros2_ws/install/setup.bash
fi
exec /opt/ros/jazzy/bin/ros2 "$@"
